services:
  mongodb_feed:
    image: mongo:noble
    container_name: mongodb_feed
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: feed
    volumes:
      - mongodb_feed_data:/data/db

volumes:
  mongodb_feed_data:
